feat: parallel limited time load of user META info
wikicensorship/tracevis pull request #71
Opened 2022-07-08 22:45 UTC by RYNEQ

Now Public IP, ASN, Region, ... are loaded using separated helper daemon process
Data are shared using shared memory between two processes
we have a minimum wait time to let helper process complete, if not ,main
process will terminate assuming meta data cannot be found (No Internet or etc)

2022-07-15 22:51 UTC, RYNEQ commented
Now everything in `get_meta` is done in separated process to overcome lack of timeout in `gethostbyname` in some cases  
call is made serially before trace
Also a privilege drop is done in separated process `nobody` and `nogroup` (this needs test in windows)

2022-07-19 10:14 UTC, bassosimone reviewed
More comments on how I think we should be dropping privileges plus a suggestion to use a separate process, if possible, since this strikes me as more robust.

2022-07-19 10:14 UTC, bassosimone commented on utils/geolocate.py
> +    p = Thread(target=get_meta, daemon=True)
Could this run in a separate process rather than thread? (Maybe I'm a bit confused at the moment, but I seem to recall a previous version of this diff was running in a separate subprocess?)

2022-07-19 10:17 UTC, bassosimone commented on utils/geolocate.py
> +            os.seteuid(65534)
Ah, also: I suggest to use `getpwnam` to obtain the correct IDs. We cannot assume they're always as such, even though they probably are. We would like to ensure we're using the right IDs.

2022-07-19 21:20 UTC, RYNEQ commented on utils/geolocate.py
> +        if os.geteuid() == 0:
I agree this is a better approach, I will change the method according to this.

2022-07-19 21:34 UTC, RYNEQ commented on utils/geolocate.py
> +    p = Thread(target=get_meta, daemon=True)
I was in a separated process and I think that would be a more robust method, In python we cannot control privilege of a Thread as the GIL system makes a lot of limitations   

But it seems Windows firewall is not very child process friendly and logs them as suspicious activity, So we had to change the method to Thread  
We also have a very rare problem with privileges when we're using threads:  
Now we spawn a thread which does the request and we wait until either it finish or the timeout expire    
We can have 3 scenarios:  
- Thread run and finish within the timeout window normally (No Problem)
- Thread get blocked forever because the lack of timeout in `gethostbyname` (No Problem)
- Thread run but finish after the timeout (Problems!)
In the 3rd scenario we drop privileges before starting thread but after timeout we need to take back `root` privileges to continue so we do so, now if the thread suddenly get unblocked the rest of its code will run in privileged mode (I tried to minimize it using a flag), we didn't have this issue in Process method as its privileges are separated from main process

2022-07-19 21:46 UTC, RYNEQ commented on utils/geolocate.py
> +            os.seteuid(65534)
We did so until https://github.com/wikicensorship/tracevis/pull/71/commits/2d1dee92af421f7b320b7c4fb8a05ef4c8b0eeb0  
As it requires loading a separated library (`pwd`) I checked the current state of BSD & Linux and it seems they are using `overflowuid` (from `/proc/sys/fs/overflowuid` ) as the `noboy` and `nogroup` id, so we thought we can reduce imported modules by hard-coding this id as it seems in current 64bit systems it is always `65534`

2022-08-28 09:42 UTC, bassosimone commented on utils/geolocate.py
> +    # windows get suspious when we spawn an independant Process
```suggestion
    # windows get suspicious when we spawn an independent Process 
```

2022-08-28 09:42 UTC, bassosimone commented on utils/geolocate.py
> +
You should drop privileges here (I don't see `drop_privileges` being called)

2022-08-28 09:42 UTC, bassosimone commented on utils/trace.py
> +SOURCE_IP_ADDRESS = get_if_addr(conf.iface)
I am not sure we should merge changes in this file: it seems some if not all of them are the result of not merging with the main branch with `-X theirs` probably. I think it's better for @xhdix to take a look and confirm.

2022-08-28 09:42 UTC, bassosimone commented on utils/geolocate.py
> +        nonlocal no_internet, public_ip, network_asn, network_name, country_code, city, is_canceled
I see lots of code duplication between the Windows and POSIX implementation. Is it possible from the respective `get_meta` functions to call  worker function that performs the lookup and then just do what is required to communicate with the parent inside the respective `get_meta` functions?

2022-08-28 23:57 UTC, RYNEQ commented on utils/geolocate.py
> +        nonlocal no_internet, public_ip, network_asn, network_name, country_code, city, is_canceled
Yes, I aggregated the querying part. thank you

2022-09-02 14:45 UTC, bassosimone requested changes

2022-09-02 14:45 UTC, bassosimone commented on utils/geolocate.py
> +    # windows get suspious when we spawn an independant Process
You should probably apply this change @xhdix @RYNEQ

2022-09-02 14:45 UTC, bassosimone commented on utils/geolocate.py
> +    if user_meta is not None :
```suggestion
    if user_meta is not None:
```

2022-09-02 14:45 UTC, bassosimone commented on utils/geolocate.py
> +    city = ""
Are these variables needed? it seems you redefine them below

2022-09-02 14:45 UTC, bassosimone commented on utils/geolocate.py
> +
You should `drop_privileges` inside the `get_meta` function

2022-09-02 14:50 UTC, xhdix commented on utils/geolocate.py
> +    # windows get suspious when we spawn an independant Process
done. Thanks

2022-09-02 16:02 UTC, xhdix commented on utils/geolocate.py
> +    city = ""
done.

2022-09-02 16:04 UTC, xhdix commented on utils/geolocate.py
> +    if user_meta is not None :
thanks

2022-09-02 16:09 UTC, xhdix commented on utils/trace.py
> +SOURCE_IP_ADDRESS = get_if_addr(conf.iface)
correct, solved. thanks!

2022-09-02 16:10 UTC, xhdix commented on utils/geolocate.py
> +
done! should be fine now. (tested the privileges in Fedora)

2022-09-02 17:08 UTC, bassosimone approved these changes
🐳

2022-09-02 18:01 UTC, xhdix commented
there is a rice condition that should be fixed. but it's a UX bug, so we are good for now and will take care of it later.
Thank you @RYNEQ and @bassosimone :heart: :hibiscus: :tada:

2022-09-02 18:02 UTC, merged